version: "3"
services:
  mongodb:
    image: mongo
    container_name: solisalim_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - db-volume:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solisalim_api
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - MONGODB_URL=mongodb://root:example@mongodb:27017/testdb?authSource=admin
      - PORT=5000
      - JWT_SECRET=SECRET
    depends_on:
      - mongodb
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: solisalim_app
    #request will forward to same url, so we only need /api to distinguish that this request will forward to our backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 3003:80
    restart: always

volumes:
  db-volume:
