version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - db-volume:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/testdb
      - PORT=5000
      - JWT_SECRET=SECRET
    depends_on:
      - mongodb
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    #request will forward to same url, so we only need /api to distinguish that this request will forward to our backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
    restart: always

volumes:
  db-volume:
