version: "3"
services:
  mongodb:
    image: mongo
    container_name: solisalim_db
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - db-volume:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solisalim_api
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      # - MONGODB_URL=mongodb://root:example@mongodb:27017/solisalim
      - MONGODB_URL=mongodb://mongodb:27017/solisalim
      - PORT=5000
      - JWT_SECRET=SECRET
    depends_on:
      - mongodb
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: solisalim_app
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 6692:80
    restart: always

volumes:
  db-volume:
